[package]
name = "sha_p2pool_grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { workspace = true }
prost = "0.11.9"
prost-types = "0.11.9"

[build-dependencies]
tonic-build = { workspace = true }
