[package]
name = "sha-p2pool"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = { version = "0.53.2", features = [
    "dns",
    "identify",
    "macros",
    "tokio",
    "serde",
    "noise",
    "tcp",
    "yamux",
    "mdns",
    "gossipsub"
] }
tokio = { version = "1.38.0", features = ["full"] }
thiserror = "1.0"
serde = "1.0.203"
anyhow = "1.0"
log = "0.4.21"
env_logger = "0.11.3"
minotari_app_grpc = { git = "https://github.com/tari-project/tari.git" }
minotari_node_grpc_client = { git = "https://github.com/tari-project/tari.git" }
tonic = "0.8.3"
#tari_common_types = "0.8.1"


